MODEL:
  META_ARCHITECTURE: "YoloV5"
  BACKBONE:
    NAME: "build_yolo_v5_backbone"
  YOLOV5:
    NUM_CLASSES: 80
    VERSION: "m"
    ANCHORS: [[10,13, 16,30, 33,23], [30,61, 62,45, 59,119], [116,90, 156,198, 373,326]]
    FOCAL_LOSS_GAMMA: 0.0
    BOX_LOSS_GAIN: 0.05
    CLS_LOSS_GAIN: 0.3
    CLS_POSITIVE_WEIGHT: 1.0
    OBJ_LOSS_GAIN: 0.7
    OBJ_POSITIVE_WEIGHT: 1.0
    LABEL_SMOOTHING: 0.0
    ANCHOR_T: 4.0
    CONF_THRESH: 0.1
    IOU_THRES: 0.65
  PIXEL_MEAN: [0.0, 0.0, 0.0]
  PIXEL_STD: [255.0, 255.0, 255.0]
INPUT:
  SIZE: 416
  HSV_H: 0.015
  HSV_S: 0.7
  HSV_V: 0.4
  DEGREES: 0.0
  TRANSLATE: 0.1
  SCALE: 0.5
  SHEAR: 0.0
  PERSPECTIVE: 0.0
  FLIPUD: 0.0
  FLIPLR: 0.5
  MOSAIC: 1.0   # IGNORED
  MIXUP: 0.0
  FORMAT: BGR
TEST:
  AUG:
    SIZE: 416
    FLIP: False
  EVAL_PERIOD: 4000
VERSION: 2
