# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Python 🐍 distributions 📦 to PyPI

on: push

jobs:
  deploy:

    runs-on: ubuntu-18.04
    container:
      image: fuliucansheng/unitorch:latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools wheel twine pytest absl-py
        if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
        python3 setup.py install
    - name: Test with unittest
      run: |
        cd tests
        python3 -m pytest .
        cd ..
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      run: |
        python3 setup.py sdist bdist_wheel
        python3 -m twine upload dist/*.tar.gz
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        TWINE_REPOSITORY: pypi
